
language: r
warnings_are_errors: false
sudo: required

dist: trusty

cache: packages

apt_packages:
  - gdal-bin
  - libproj-dev
  - libgdal-dev
  - libudunits2-dev

after_success:
  - Rscript -e 'covr::codecov()'




